In [6]:
print('Hello World !')

Hello World !


In [7]:
compteCourant = 500
compteEpargne = 1000

# ajouter 100 à notre épargne (Yeah!)
compteEpargne = compteEpargne + 100

# enlever 50 de notre compte courant (Snif)
compteCourant = compteCourant - 50

# calculer le nombre de jours à économiser pour atteindre 5000€
nombreJoursEconomiser = (5000 - compteCourant) / 500

# mettre à jour notre compte courant (encore) après les gains/pertes journaliers
compteCourant = compteCourant + (30 - 10) * 7

In [8]:
compteCourant

590

In [9]:
compteEpargne

1100

In [10]:
print(compteEpargne % 500) # -> 100
# 1100 = 500 * 2 + 100, donc 1100 % 500 = le reste = 100

print(9 ** 3) # -> 729, 9*9*9 = 729

print(compteEpargne // 500) # -> 2
# 1100 = 500 * 2 + 100, donc 1100 // 500 = résultat division entière = 2

100
729
2


In [11]:
prenom = "Benjamin"
pourcentageActivite = 72.3
adresse = "7 Cité Paradis, 75010 Paris"

In [12]:
taux = 0.75
interets = compteEpargne * (taux/100)
print(interets)

#permet de changer le type de variable
interets = int(interets)
print(interets)

8.25
8


In [13]:
#concaténer du texte avec du numérique
# ne pas oublier de mettre les espaces

ville = "Sydney"
nombreVoyages = 5
histoire = "J'ai déjà été à " + ville + " " + str(nombreVoyages) + " fois"
print(histoire) # => "J'ai déjà été à Syndey 5 fois"

J'ai déjà été à Sydney 5 fois


In [14]:
#**les listes**

nomClient = ['Georges Dupont', 'Luc Martin', 'Lucas Anderson', 'Alexandre Petit']
# assigner la valeur 'Georges Dupond' au premier nom dans notre liste
# c'est donc l'indice 0, car les indices commencent à 0 en python !
nomClient[0] = 'Georges Dupond'

In [15]:
# afficher le dernier élément
print(nomClient[-1])

# accéder du second élément au 3ème
print(nomClient[1:3])

# accéder à tous les éléments du début jusqu'au second
print(nomClient[:2])

Alexandre Petit
['Luc Martin', 'Lucas Anderson']
['Georges Dupond', 'Luc Martin']


In [16]:
liste = []
liste.append(7) # -> [7]
liste.append(5) # -> [7, 5]
liste.insert(1,12) # [7, 12, 5]
liste[0] = 4 # -> [4, 12, 5]
liste.remove(12) # [4, 5]
liste.index(5) # affiche 1
liste.extend([1, 2, 3]) # [4, 5, 1, 2, 3]
del liste[3] # [4, 5, 1, 3]

In [17]:
#Décomposons ces quelques lignes :
#les trois premières lignes correspondent à ce qui a été vu avant ;

#vous ajoutez ensuite l’entier 12 à l’indice 1. L’ancienne valeur en position 1 est déplacée en position 2 ;

#vous remplacez ensuite la valeur à l’indice 0 par 4 ;

#avec la méthode .remove(), vous retirez l’entier 12 de notre liste ;

#vous demandez ensuite l’indice du premier élément 5 dans notre liste (ici en seconde position, donc retourne 1) ;

#vous ajoutez la liste  [1, 2, 3]  à la suite de notre liste initiale ;

#et vous supprimez finalement l’élément situé en position 4 dans notre liste.

#Cela vous laisse finalement avec la liste finale : [4, 5, 1, 3].

In [18]:
#les Divtionnaires

In [2]:
comptes = {"Georges Dupont": 10000, "Luc Martin": 150, "Lucas Anderson": 300, "Alexandre Petit": 1800.74}
print(comptes["Luc Martin"])

150


In [3]:
print(comptes)

{'Georges Dupont': 10000, 'Luc Martin': 150, 'Lucas Anderson': 300, 'Alexandre Petit': 1800.74}


In [4]:
comptes['Georges Dupont'] -= 2000 # je soustrais 2000 au compte de Georges
comptes['Cyril Andreje'] = 1000 # j'ajoute un nouvel individu dans mon dictionnaire
print(comptes['Cyril Andreje']) # j'affiche la valeur du compte de Cyril

1000


In [5]:
comptes.pop('Luc Martin') # supprime Luc Martin de notre dictionnaire

150

In [23]:
len(comptes)

4

In [24]:
mon_tuple = (1, 2, 3, 'a', 'b')

In [25]:
print(mon_tuple[1])
print(mon_tuple[4]) 

2
b


In [26]:
a, b = (1, 'pomme')
print(a) # -> 1
print(b) # -> 'pomme'

1
pomme


In [27]:
print(mon_tuple)

(1, 2, 3, 'a', 'b')


In [28]:
#la structure conditionnelle

In [29]:
nom = input('Quel est ton nom, cher(e) inconnu(e) ?')

if len(nom) > 0:
    print("Hello", nom, "!")
else:
    print("Hello World !")

Hello Antho !


In [30]:
maListe = [4, 2, 3, 2, 10]
maListeDeString = ["a", "b", "c", "d"]
monString = "La météo est vraiment bien aujourd'hui !"

4 in maListe # True
0 in maListe # False
0 in maListeDeString # False
"c" in maListeDeString # True
"e" in maListeDeString # False
"météo" in monString # True
"vraiment" in monString # True
"pluie ?" in monString # False

False

In [31]:
compte = input("Quel est le soldes de votre compte ?")
compte = int(compte) # transformer la réponse en entier

if compte >= 10000:
    print("Prêt accordé !")
elif compte >= 100 and compte < 10000:
    print("Prêt en cours de validation : à l'étude")
else:
    print("Prêt refusé")

Prêt en cours de validation : à l'étude


In [32]:
monString = "Eléments"

for elt in monString:
    print(elt)

E
l
é
m
e
n
t
s


In [33]:
nombreArbres = 0

while nombreArbres < 10:
    nombreArbres += 1
    print("J'ai planté", nombreArbres, "arbres")
    
print("J'ai une chouette forêt !")

J'ai planté 1 arbres
J'ai planté 2 arbres
J'ai planté 3 arbres
J'ai planté 4 arbres
J'ai planté 5 arbres
J'ai planté 6 arbres
J'ai planté 7 arbres
J'ai planté 8 arbres
J'ai planté 9 arbres
J'ai planté 10 arbres
J'ai une chouette forêt !


In [34]:
i = 0
while i < 5:
    print("OpenClassRooms est vraiment top !")
    i += 1

OpenClassRooms est vraiment top !
OpenClassRooms est vraiment top !
OpenClassRooms est vraiment top !
OpenClassRooms est vraiment top !
OpenClassRooms est vraiment top !


In [35]:
for i in range(10):
    # instructions réalisées à chaque itération
    print(i)
    if (i == 2) or (i == 5):
        print("Cas spécial")
        continue 
    # instructions non exécutées si i == 2 or 5 
    print("i != 2 & i != 5")


0
i != 2 & i != 5
1
i != 2 & i != 5
2
Cas spécial
3
i != 2 & i != 5
4
i != 2 & i != 5
5
Cas spécial
6
i != 2 & i != 5
7
i != 2 & i != 5
8
i != 2 & i != 5
9
i != 2 & i != 5


In [36]:
panier = ["pomme", "orange", "banane"]

for fruit in panier:
    if fruit == "orange":
        print("J'ai une", fruit, "!")
        break

J'ai une orange !


#Les Modules

In [37]:
'''
Module geometry.py
'''
# variables
pi = 3.14159265359
phi = 1.6180

# fonction qui calcule l'aire
def aire(obj):
    if type(obj) == carre:
        return obj.a**2

# definitions de quelques classes
class carre(object):
    def __init__(self,a):
        self.a = a

class triangle(object):
    def __init__(self,a,b,c):
        self.a = a
        self.b = b
        self.c = c

In [38]:
ensoleille = False
neige = True
if ensoleille:
    print("on va à la plage !")
elif neige:
    print("on fait un bonhomme de neige")
else:
    print("on reste à la maison !")

on fait un bonhomme de neige


In [39]:
avec_soleil = True
en_semaine = False
if avec_soleil and not en_semaine:
    print("on va à la plage !")
elif avec_soleil and en_semaine:
    print("on va au travail !")
else:
    print("on reste à la maison !")

on va à la plage !


In [40]:
fruit = "pomme"
match fruit:
    case "pomme":
        print("J'aime les pommes !")
    case "banane":
        print("Je n'aime pas les bananes.")
    case "orange":
        print("Les oranges sont bonnes pour la santé.")
    case _:
        print("Je ne connais pas ce fruit.")

J'aime les pommes !


In [41]:

nombre_a_gauche = input ("Entrez un nombre entier: ")
nombre_a_droite = input ("Entrez un nombre entier: ")
operation = input ("Entrez l'opération souhaitée : +, -, / ou *" )

resultat = 0

if not nombre_a_gauche.isnumeric() or not nombre_a_droite.isnumeric() :
    print("Erreur ! Entrez un nombre entier SVP")
else:
    nombre_a_droite = int(nombre_a_droite)
    nombre_a_gauche = int(nombre_a_gauche)

match operation :
    case "+" :
        resultat = nombre_a_droite + nombre_a_gauche
    case "-" :
        resultat = nombre_a_droite - nombre_a_gauche
    case "*" :
        resultat = nombre_a_droite * nombre_a_gauche
    case "/" :
        resultat = nombre_a_droite / nombre_a_gauche
        if nombre_a_gauche == 0 or nombre_a_droite == 0 :
            print("Ne pas diviser par zéro")
        else :  resultat = nombre_a_gauche / nombre_a_droite
    case _:
        print("Erreur: le symbole d'opération doit être '+', '-', '*' ou '/'.")

print(resultat)

3


In [42]:
for x in range(10):
    print(f"{x} bouteilles de bières au mur !")

0 bouteilles de bières au mur !
1 bouteilles de bières au mur !
2 bouteilles de bières au mur !
3 bouteilles de bières au mur !
4 bouteilles de bières au mur !
5 bouteilles de bières au mur !
6 bouteilles de bières au mur !
7 bouteilles de bières au mur !
8 bouteilles de bières au mur !
9 bouteilles de bières au mur !


In [43]:
ensemble_de_nombres = input("Entrez une liste de nombres, séparés par des virgules")
ensemble_de_nombres = ensemble_de_nombres.split(",")
print('liste de nombre :',ensemble_de_nombres)

liste de nombre : ['+']


In [44]:
sommes = 0
for nombre in ensemble_de_nombres :
    sommes += int(nombre)
print("la somme des nombre est de", sommes)

ValueError: invalid literal for int() with base 10: '+'

In [ ]:
moyenne = 0
moyenne = sommes / len(ensemble_de_nombres)

print("la mmoyenne est de", int(moyenne))

la mmoyenne est de 3


In [ ]:
nombre_sup_moyenne = 0
for nombre in ensemble_de_nombres :
    if int(nombre) <  moyenne:
        nombre_sup_moyenne += 1 
print("Voici le nombre supérieur à la moyenne :", nombre_sup_moyenne)



Voici le nombre supérieur à la moyenne : 2


In [ ]:
nombre_pairs = 0 
i = 0

while i < len(ensemble_de_nombres):
    if int(ensemble_de_nombres[i]) % 2 == 0:
        nombre_pairs += 1
    i += 1
print(nombre_pairs)

2


In [ ]:
def salaire_mensuel(salaire_annuel) :
    return salaire_annuel / 11 

def salaire_hebdomadaire(salaire_mensuel):
    return salaire_mensuel / 4 


def salaire_horaire(salaire_hebdomadaire, heures_travaillees):
    return salaire_hebdomadaire / heures_travaillees

def main():
    salaire_annuel = float(input("Veuillez saisir votre salaire annuel svp"))
    heures_travaillees = float(input("Veuillez saisir les heures travaillées par semaine svp"))

    mensuel = salaire_mensuel(salaire_annuel)
    print(mensuel)

    hebdomadaire = salaire_hebdomadaire(mensuel)
    print(hebdomadaire)

    horaire = salaire_horaire(hebdomadaire, heures_travaillees)
    print(salaire_horaire)

    print("Votre salaire horaire est de",horaire, "euros")


In [ ]:
def salaire_mensuel(salaire_annuel):
    return salaire_annuel / 12


# Définition de la fonction salaire_hebdomadaire
def salaire_hebdomadaire(salaire_mensuel):
    return salaire_mensuel / 4


# Définition de la fonction salaire_horaire
def salaire_horaire(salaire_hebdomadaire, heures_travaillees):
    return salaire_hebdomadaire / heures_travaillees


def main():
    # Demande à l'utilisateur de saisir son salaire annuel
    salaire_annuel = float(input("Entrez votre salaire annuel : "))
    # Demande à l'utilisateur de saisir le nombre d'heures travaillées par semaine
    heures_travaillees = float(
        input("Entrez le nombre d'heures travaillées par semaine : "))

    # Calcul du salaire horaire
    mensuel = salaire_mensuel(salaire_annuel)
    hebdomadaire = salaire_hebdomadaire(mensuel)
    horaire = salaire_horaire(hebdomadaire, heures_travaillees)

    # Affichage du résultat
    print("Votre salaire horaire est de", horaire, "euros.")


In [ ]:
pip install request2

Defaulting to user installation because normal site-packages is not writeable
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
   ---------------------------------------- 0.0/64.9 kB ? eta -:--:--
   ---------------------------------------- 64.9/64.9 kB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/163.0 kB ? eta -:--:--
   ---------------------------------------- 163.0/163.0 kB 9.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/100.4 kB ? eta -:--:--
   ---------------------------------------- 100.4/100.4 kB ? eta 0:00:00
   ---------------------------------------- 0.0/66.8 kB ? eta -:--:--
   ---------------------------------------- 66.8/66.8 kB 3.8 MB/s eta 0:00:00
 


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\A-Bez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import requests

url = "https://www.gov.uk/search/news-and-communications"
page = requests.get(url)

# Voir le code html source
print(page.content)

b'<!DOCTYPE html>\n<!--[if lt IE 9]><html class="lte-ie8 govuk-template" lang="en"><![endif]--><!--[if gt IE 8]><!--><html class="govuk-template" lang="en">\n<!--<![endif]-->\n  <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">\n<meta property="og:description" content="Find news and communications from government">\n<meta property="og:title" content="News and communications">\n<meta property="og:url" content="https://www.gov.uk/search/news-and-communications">\n<meta property="og:type" content="article">\n<meta property="og:site_name" content="GOV.UK">\n<meta name="govuk:base_title" content="News and communications - GOV.UK">\n<meta name="govuk:search-result-count" content="129851">\n<meta name="twitter:card" content="summary">\n<meta name="govuk:public-updated-at" content="2021-02-09T10:00:56+00:00">\n<meta name="govuk:updated-at" content="2021-02-09T10:00:56+00:00">\n<meta name="govuk:first-published-at" content="2019-02-01T12:31:51+00:00">\n<meta name="govu

In [ ]:
pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\A-Bez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import requests

from bs4 import BeautifulSoup

url = "https://www.gov.uk/search/news-and-communications"
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

In [ ]:
descriptions = soup.find_all("p", class_="gem-c-document-list__item-description")

In [ ]:
descriptions

[<p class="gem-c-document-list__item-description">Bringing together professionals from across the public sector, online and in person, to uncover the secrets to exceptional workplace experiences this September.</p>,
 <p class="gem-c-document-list__item-description">Defence Infrastructure Organisation (DIO) has awarded Willmot Dixon a contract to deliver vital infrastructure for the rebasing of the 1st Military Working Dog (MWD) Regiment from St George’s Barracks to Kendrew Barracks in …</p>,
 <p class="gem-c-document-list__item-description">At the OSCE Forum for Security Cooperation (FSC), Ambassador Neil Holland calls on Russia to end its war, withdraw all its forces from all of Ukraine and to re-engage in dialogue and risk-reduction.</p>,
 <p class="gem-c-document-list__item-description">Publication of the Bona Vacantia accounts for 2023 – 2024</p>,
 <p class="gem-c-document-list__item-description">Father and son sentenced for Bounce Back Loan abuse </p>,
 <p class="gem-c-document-li

In [ ]:
with open("index.html", 'r') as file:
    soup = BeautifulSoup(file, 'html.parser')

In [ ]:
soup

<!DOCTYPE html>

<html>
<head>
<title>Exercice extraction HTML</title>
</head>
<body>
<h1>Bienvenue sur notre site web</h1>
<p>Voici une liste de nos produits :</p>
<ul>
<li>
<h2>Produit 1</h2>
<p>Prix : 10€</p>
<p>Description : Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
</li>
<li>
<h2>Produit 2</h2>
<p>Prix : 20€</p>
<p>Description : Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</li>
<li>
<h2>Produit 3</h2>
<p>Prix : 30€</p>
<p>Description : Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
</li>
</ul>
</body>
</html>

In [ ]:
titre = soup.title.string

In [ ]:
h1_text = soup.h1.string

In [ ]:
produits = soup.find_all("li")
produits_list = []
for produit in produits:
    nom = produit.h2.string
    prix = produit.find("p", string=lambda s: "Prix" in s).string
    produits_list.append((nom, prix))

In [ ]:
description_liste = []
for produit in produits:
    description = produit.find("p", string=lambda s: "Description" in s).string
    description_liste.append(description)

In [ ]:
print("Titre de la page :", titre)
print("Texte de la balise h1 :", h1_text)
print("Liste des produits :", produits_list)
print("Liste des descriptions de produits :", description_liste)

Titre de la page : Exercice extraction HTML
Texte de la balise h1 : Bienvenue sur notre site web
Liste des produits : [('Produit 1', 'Prix : 10€'), ('Produit 2', 'Prix : 20€'), ('Produit 3', 'Prix : 30€')]
Liste des descriptions de produits : ['Description : Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Description : Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Description : Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.']


# Étape 3 : Conversion des prix en dollars
for i, (name, price) in enumerate(products_list):
    # Supprimer les caractères non numériques de la chaîne de prix
    euro_price_str = ''.join(filter(str.isdigit, price.split()[2])) 
    euro_price = int(euro_price_str)
    dollar_price = euro_price * 1.2
    products_list[i] = (name, f"{dollar_price}$")

# Étape 4 : Affichage de la nouvelle liste avec les prix en dollars
print("Liste des produits :", products_list)

In [ ]:
fichier = open("hello.txt", "w")
fichier.write("Hello, world!")
fichier.close()

NumPy

In [48]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [ ]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 330.3 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.9 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 464.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/16.3 MB ? eta -:--:--
    --------------------------------------- 0.2/16.3 MB 7.3 MB/s eta 0:00:03
   - -------------------------------------- 0.6/16.3 MB 8.1 MB/s eta 0:00:02
   -- ------------------------------------- 1.2/16.3 MB 9.2 MB/s eta 0:00:02
   ---- ----------------------------------- 1.8/16.3 MB 10.2 MB/s eta 0:00:02
   ------ --------------------------------- 2.6/16.3 MB 11.7 MB/s eta 0:00:02
   -------- ------------------------------- 3.6/16.3 MB 13.3 MB/s eta 0:00:01
   ----------- ---------------------------- 4.7/16.3 MB 15.2 MB/s eta 0:00:


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\A-Bez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [46]:
import numpy as np

In [49]:
revenus_array = np.array(revenus)
revenus_array


array([1800, 1500, 2200, 3000, 2172])

In [50]:
# pour accéder au 5ème élement
revenus_array[4]

np.int64(2172)

In [ ]:
# pour accéder au dernier élément
revenus_array[-1]

np.int64(2172)

In [ ]:
# On peut aussi modifier les valeurs
revenus_array[1] = 1900

In [ ]:
# Les 3 premiers éléments
print(revenus_array[:3])

[1800 1900 2200]


In [ ]:
# Les éléments à partir de l’indice 2
print(revenus_array[2:])

[2200 3000 2172]


In [ ]:
# Un élément sur deux
print(revenus_array[::2])

[1800 2200 2172]


In [ ]:
revenus_array[revenus_array > 2000]


array([2200, 3000, 2172])

In [ ]:
revenus_array[(revenus_array > 2000) & (revenus_array < 3000)]


array([2200, 2172])

In [ ]:
revenus_array.shape
# (5,) on a array contenant 5 éléments

(5,)

In [ ]:
# calculer la moyenne
revenus_array.mean()

np.float64(2214.4)

In [ ]:
# calculer le maximum (ou le minimum) :
revenus_array.max()
revenus_array.min()

np.int64(1800)

In [ ]:
# accéder à l’indice de l’élement minimum (ou maximum) :
revenus_array.argmin()
revenus_array.argmax()

np.int64(3)

In [ ]:
# ordonner par ordre croissant :
revenus_array.sort()
print(revenus_array)

[1800 1900 2172 2200 3000]


In [ ]:
# calculer la somme :
revenus_array.sum()

np.int64(11072)

In [ ]:
tab1 = np.array([[1, 2],
    [3, 4],
    [5, 6]])

tab2 = np.array([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
import numpy as np

In [ ]:
# un tableau de 3x5 rempli de 1
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# un tableau de 4 lignes et de 4 colonnes contenant que des 0
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# un tableau de 6x3 rempli de valeurs aléatoires comprises entre 0 et 1
np.random.random((6, 3))

array([[0.58954166, 0.43234728, 0.40777668],
       [0.45371384, 0.63879086, 0.0646735 ],
       [0.83023129, 0.56960939, 0.30525291],
       [0.08193958, 0.62485328, 0.38767397],
       [0.70106059, 0.61408222, 0.26145213],
       [0.26332944, 0.73884125, 0.23619675]])

In [ ]:
# un tableau de 3x3 rempli de valeurs aléatoires entières, comprises entre 1 et 10
np.random.randint(1, 10, size=(3, 3))

array([[2, 8, 1],
       [9, 8, 8],
       [5, 3, 1]], dtype=int32)

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])

A+B

array([[ 6, 12],
       [18, 24]])

In [ ]:
# Produit matriciel
A@B

array([[ 35,  50],
       [ 75, 110]])

In [ ]:
# ou bien
AC = np.dot(A,B)

In [ ]:
AC

array([[ 35,  50],
       [ 75, 110]])

In [ ]:
louise = [1900, 31, 1]
#pour ajouter : array = np.vstack((array, louise))

In [ ]:
a = np.linspace(5, 10, 11)

a

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

PANDAS

In [ ]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.2/11.5 MB 5.6 MB/s eta 0:00:03
   - -------------------------------------- 0.6/11.5 MB 7.0 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.5 MB 7.9 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/11.5 MB 9.0 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/11.5 MB 10.4 MB/s eta 0:00:01
   ----------- ---------------------------- 3.2/11.5 MB 12.0 MB/s eta 0:00:01
   -------------- ------------------------- 4.3/11.5 MB 13.7 MB/s eta 0:00:01
   ------------------- -------------------- 5.7/11.5 MB 15.8 MB/s eta 0:00:01
   ------------------------- -------------- 7.5/11.5 MB 18.4 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 21.4 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.5 MB 29.8 MB/s eta 0:00:


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\A-Bez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd

In [ ]:
data_csv= pd.read_csv('clients.csv')
data_csv.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [ ]:
data_json= pd.read_json('clients.json')
data_json.head()

identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [ ]:
data_json.shape

(228, 4)

In [ ]:
dim = data_json.shape
print(dim[0]) 
print(dim[1]) 

228
4


In [ ]:
data_json.dtypes

identifiant     int64
email          object
nom            object
genre          object
dtype: object

In [ ]:
#transformer un data frame en Array Numpy

In [ ]:
clients_array = data_json.values
display(clients_array)

array([[0, 'LaurentDagenais@rhyta.com', 'Laurent Dagenais', 'M'],
       [1, 'GuyMarois@fleckens.hu', 'Guy Marois', 'M'],
       [2, 'BeaufortLesage@einrot.com', 'Beaufort Lesage', 'M'],
       [3, 'RussellDurand@armyspy.com', 'Russell Durand', 'M'],
       [4, 'AlexisRiel@rhyta.com', 'Alexis Riel', 'M'],
       [5, 'LeonLapresse@cuvox.de', 'Leon Lapresse', 'M'],
       [6, 'OrvilleRouthier@gustr.com', 'Orville Routhier', 'M'],
       [7, 'AgramantPepin@dayrep.com', 'Agramant Pepin', 'M'],
       [8, 'AiglentinaLambert@fleckens.hu', 'Aiglentina Lambert', 'F'],
       [9, 'TheodoreClavet@teleworm.us', 'Theodore Clavet', 'M'],
       [10, 'ByronLefebvre@jourrapide.com', 'Byron Lefebvre', 'M'],
       [11, 'FlorusDevoe@einrot.com', 'Florus Devoe', 'M'],
       [12, 'NormandArsenault@armyspy.com', 'Normand Arsenault', 'M'],
       [13, 'AcelineHughes@jourrapide.com', 'Aceline Hughes', 'F'],
       [14, 'GastonBrisette@superrito.com', 'Gaston Brisette', 'M'],
       [15, 'AgateGrandbois@gus

In [ ]:
data = data_json

In [ ]:
data["email"]

0            LaurentDagenais@rhyta.com
1                GuyMarois@fleckens.hu
2            BeaufortLesage@einrot.com
3            RussellDurand@armyspy.com
4                 AlexisRiel@rhyta.com
                    ...               
223    ClaudeDandonneau@jourrapide.com
224      ApollineMichaud@superrito.com
225         PascalineBeaudry@rhyta.com
226       FleurCaouette@jourrapide.com
227        FrancisMasse@jourrapide.com
Name: email, Length: 228, dtype: object

In [ ]:
email = data["email"]

In [45]:
variables = ["nom", "email"]
data[variables]

NameError: name 'data' is not defined

In [ ]:
#créer une colonne

data['id'] = data['identifiant'] + 1
data.head()

identifiant                      email               nom genre  id
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M   1
1            1      GuyMarois@fleckens.hu        Guy Marois     M   2
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M   3
3            3  RussellDurand@armyspy.com    Russell Durand     M   4
4            4       AlexisRiel@rhyta.com       Alexis Riel     M   5

In [ ]:
#supprimer une colonne
#data.drop(columns='id')

#renommer une colonne  
data.rename(columns={'identifiant': 'iden'})

iden                            email                nom genre   id
0       0        LaurentDagenais@rhyta.com   Laurent Dagenais     M    1
1       1            GuyMarois@fleckens.hu         Guy Marois     M    2
2       2        BeaufortLesage@einrot.com    Beaufort Lesage     M    3
3       3        RussellDurand@armyspy.com     Russell Durand     M    4
4       4             AlexisRiel@rhyta.com        Alexis Riel     M    5
..    ...                              ...                ...   ...  ...
223   223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F  224
224   224    ApollineMichaud@superrito.com   Apolline Michaud     F  225
225   225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F  226
226   226     FleurCaouette@jourrapide.com     Fleur Caouette     F  227
227   227      FrancisMasse@jourrapide.com      Francis Masse     M  228

[228 rows x 5 columns]

In [ ]:
data['identifiant'].astype(float)

0        0.0
1        1.0
2        2.0
3        3.0
4        4.0
       ...  
223    223.0
224    224.0
225    225.0
226    226.0
227    227.0
Name: identifiant, Length: 228, dtype: float64

In [ ]:
#trier selon l’identifiant par ordre décroissant :
data.sort_values('identifiant', ascending = False)

identifiant                            email                nom genre  \
227          227      FrancisMasse@jourrapide.com      Francis Masse     M   
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F   
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F   
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F   
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F   
..           ...                              ...                ...   ...   
4              4             AlexisRiel@rhyta.com        Alexis Riel     M   
3              3        RussellDurand@armyspy.com     Russell Durand     M   
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M   
1              1            GuyMarois@fleckens.hu         Guy Marois     M   
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M   

      id  
227  228  
226  227  
225  226  
224  225  
223  224  
..   ...  
4      5  
3      4  
2      3  
1      2  
0      1  

[228 rows x 5 columns]

In [ ]:
# trier selon le genre puis le nom, par ordre croissant :
data.sort_values(['genre', 'nom'])

identifiant                         email                 nom genre   id
13            13  AcelineHughes@jourrapide.com      Aceline Hughes     F   14
135          135     AdelaideBrousse@gustr.com    Adelaide Brousse     F  136
189          189        AdeleClavette@cuvox.de      Adele Clavette     F  190
15            15      AgateGrandbois@gustr.com     Agate Grandbois     F   16
180          180          AgnesBriard@cuvox.de        Agnes Briard     F  181
..           ...                           ...                 ...   ...  ...
167          167      VerneyCourse@armyspy.com       Verney Course     M  168
127          127           VickDavid@gustr.com          Vick David     M  128
192          192   XarlesCaisse@jourrapide.com       Xarles Caisse     M  193
174          174   ZacharieDuplessis@rhyta.com  Zacharie Duplessis     M  175
100          100   ZdenekVadnais@superrito.com      Zdenek Vadnais     M  101

[228 rows x 5 columns]

In [ ]:
data.sort_values(['genre', 'nom'], ascending=[True, False])

identifiant                           email                nom genre   id
53            53         ZurieTheberge@gustr.com     Zurie Theberge     F   54
112          112            ZoeLeclair@gustr.com        Zoe Leclair     F  113
64            64            YvetteDAvis@cuvox.de      Yvette D Avis     F   65
18            18       YseultCharest@armyspy.com     Yseult Charest     F   19
158          158        YoletteMoreau@dayrep.com     Yolette Moreau     F  159
..           ...                             ...                ...   ...  ...
62            62          AleronBerard@rhyta.com      Aleron Berard     M   63
204          204          AimeMarseau@dayrep.com       Aime Marseau     M  205
16            16  AgricanFoucault@jourrapide.com   Agrican Foucault     M   17
7              7        AgramantPepin@dayrep.com     Agramant Pepin     M    8
202          202      AgramantGrandpre@rhyta.com  Agramant Grandpre     M  203

[228 rows x 5 columns]

In [ ]:
# sélectionner le nom des 10 premiers clients :
data.iloc[:10, 2]

0      Laurent Dagenais
1            Guy Marois
2       Beaufort Lesage
3        Russell Durand
4           Alexis Riel
5         Leon Lapresse
6      Orville Routhier
7        Agramant Pepin
8    Aiglentina Lambert
9       Theodore Clavet
Name: nom, dtype: object

In [ ]:
# sélectionner l’email et le nom des 10 clients suivants :
data.iloc[10:20, 1:3]

email                 nom
10    ByronLefebvre@jourrapide.com      Byron Lefebvre
11          FlorusDevoe@einrot.com        Florus Devoe
12    NormandArsenault@armyspy.com   Normand Arsenault
13    AcelineHughes@jourrapide.com      Aceline Hughes
14    GastonBrisette@superrito.com     Gaston Brisette
15        AgateGrandbois@gustr.com     Agate Grandbois
16  AgricanFoucault@jourrapide.com    Agrican Foucault
17   PrunellaJosseaume@armyspy.com  Prunella Josseaume
18       YseultCharest@armyspy.com      Yseult Charest
19          DorotheeAupry@cuvox.de      Dorothee Aupry

In [ ]:
# sélectionner l’e-mail et le genre des 10 derniers clients :
data.iloc[-10:, [1, 3]]

email genre
218           MinetteRoy@fleckens.hu     F
219         RoslynChalifour@cuvox.de     M
220          KarelBazinet@einrot.com     M
221      JosetteBordeleau@einrot.com     F
222         LangleyCaron@armyspy.com     M
223  ClaudeDandonneau@jourrapide.com     F
224    ApollineMichaud@superrito.com     F
225       PascalineBeaudry@rhyta.com     F
226     FleurCaouette@jourrapide.com     F
227      FrancisMasse@jourrapide.com     M

In [ ]:
data.groupby('genre').sum()

identifiant                                              email  \
genre                                                                   
F            14209  AiglentinaLambert@fleckens.huAcelineHughes@jou...   
M            11669  LaurentDagenais@rhyta.comGuyMarois@fleckens.hu...   

                                                     nom     id  
genre                                                            
F      Aiglentina LambertAceline HughesAgate Grandboi...  14327  
M      Laurent DagenaisGuy MaroisBeaufort LesageRusse...  11779

In [ ]:
pip install matplotlib


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/165.9 kB ? eta -:--:--
     --------- ----------------------------- 41.0/165.9 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 165.9/165.9 kB 3.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------- ----------------------------- 2.0/8.0 MB 65.4 MB/s eta 0:00:01
   ------------------------------------- -- 7.5/8.0 MB 96.1 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 73.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/189.9 kB ? eta -:--:--
   --------------------------------------- 189.9/189.9 kB 12.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------------------- -------- 1.7/2.2 MB 36.2 MB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.2 MB 18.5 MB/s eta 0:00:01
   ------------


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: C:\Users\A-Bez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [6]:
import matplotlib.pyplot as plt

In [8]:
plt.scatter(prets['revenu'], prets['taux_endettement'])

NameError: name 'prets' is not defined

In [1]:
pip freeze

asttokens==2.4.1
beautifulsoup4==4.12.3
certifi==2024.7.4
charset-normalizer==3.3.2
colorama==0.4.6
comm==0.2.2
contourpy==1.2.1
cycler==0.12.1
debugpy==1.8.2
decorator==5.1.1
executing==2.0.1
fonttools==4.53.1
idna==3.7
ipykernel==6.29.5
ipython==8.26.0
jedi==0.19.1
jupyter_client==8.6.2
jupyter_core==5.7.2
kiwisolver==1.4.5
matplotlib==3.9.1
matplotlib-inline==0.1.7
nest-asyncio==1.6.0
numpy==2.0.1
packaging==24.1
pandas==2.2.2
parso==0.8.4
pillow==10.4.0
platformdirs==4.2.2
prompt_toolkit==3.0.47
psutil==6.0.0
pure-eval==0.2.2
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
pyzmq==26.0.3
request2==0.2
requests==2.32.3
six==1.16.0
soupsieve==2.5
stack-data==0.6.3
tornado==6.4.1
traitlets==5.14.3
tzdata==2024.1
urllib3==2.2.2
wcwidth==0.2.13
Note: you may need to restart the kernel to use updated packages.


In [1]:
class Rectangle:
    def __init__(self, length, width, color="red"):
        self.length = length
        self.width = width
        self.color = color